#!/usr/bin/env bash

# General
alias fzfbat="fzf --preview 'bat --color=always {}'"
alias fzfenv="printenv | fzf | cut -d '=' -f 2 | pbcopy"
alias fzfhist="history | fzf --tac | sed 's/^[[:space:]]*[0-9][0-9]*[[:space:]]*//' | pbcopy"
alias fzfps="ps u | fzf | pbcopy"
alias duf="du -sh ./* | sort -hr"
alias dud="du -h -d 1 | sort -hr"
alias rsp="rsync -av --progress"

# Git
alias fzfgc="git branch | fzf | xargs git checkout"
alias fzfgl="git log --oneline | fzf | pbcopy"
alias glg="git log --oneline --graph --decorate"

# Python
alias avenv="source .venv/bin/activate"
alias cvenv="python -m venv .venv"
alias fzfpip="pip freeze | fzf | pbcopy"
alias fzfuvpip="uv pip freeze | fzf | pbcopy"
